import { useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, ArrowLeftRight, Plus, TrendingDown, TrendingUp, Wallet, Target, AlertTriangle, ChevronRight } from "lucide-react";
import { Link } from "wouter";
import AppShell from "../components/AppShell";
import SectionHeader from "../components/SectionHeader";
import StatCard from "../components/StatCard";
import TransactionForm from "../components/TransactionForm";
import { useFinance } from "../context/FinanceContext";
import { formatCurrency, formatDate } from "../lib/utils";
export default function Dashboard(){
 const {transactions,accountBalances,totalBalance,monthlyTotals,previousMonthTotals,weeklySpending,categoryTotals,currentBudgets,goals,savingsRate,preferences}=useFinance();const [open,setOpen]=useState(false);
 const change=previousMonthTotals.expenses?((monthlyTotals.expenses-previousMonthTotals.expenses)/previousMonthTotals.expenses)*100:null;const max=Math.max(...weeklySpending.map(x=>x.amount),1);const top=categoryTotals[0];
 const recent=useMemo(()=>[...transactions].sort((a,b)=>`${b.date}${b.createdAt}`.localeCompare(`${a.date}${a.createdAt}`)).slice(0,6),[transactions]);
 return <AppShell><SectionHeader eyebrow="Live overview" title="Money, in context." description="Your financial picture updates the moment you record something." action={<button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={16}/> Add transaction</button>}/>
 <section className="hero-balance"><div><p className="eyebrow">Total balance</p><div className="balance-number">{formatCurrency(totalBalance,preferences.currency)}</div><p className="muted mt-2">Across {accountBalances.length} account{accountBalances.length!==1?"s":""}</p></div><div className="balance-meta"><div><span>Monthly income</span><strong className="positive">{formatCurrency(monthlyTotals.income,preferences.currency)}</strong></div><div><span>Monthly spending</span><strong>{formatCurrency(monthlyTotals.expenses,preferences.currency)}</strong></div><div><span>Savings rate</span><strong>{savingsRate.toFixed(0)}%</strong></div></div></section>
 <div className="grid gap-4 sm:grid-cols-3 mt-5"><StatCard label="Income this month" value={formatCurrency(monthlyTotals.income,preferences.currency)} hint={`${transactions.filter(t=>t.type==="income"&&t.date?.startsWith(new Date().toISOString().slice(0,7))).length} entries`} accent/><StatCard label="Spent this month" value={formatCurrency(monthlyTotals.expenses,preferences.currency)} hint={change===null?"No previous month baseline":`${Math.abs(change).toFixed(0)}% ${change>0?"above":"below"} last month`}/><StatCard label="Top category" value={top?.category||"—"} hint={top?formatCurrency(top.amount,preferences.currency):"Add expenses to discover patterns"}/></div>
 <div className="grid gap-5 mt-5 xl:grid-cols-[1.45fr_.55fr]">
  <section className="panel p-6 sm:p-7"><div className="panel-head"><div><p className="eyebrow">Spending rhythm</p><h2 className="panel-title">Last 7 days</h2></div><span className="live-badge">LIVE</span></div><div className="chart-bars">{weeklySpending.map((d,i)=><div key={d.date} className="bar-col"><div className="bar-wrap"><div className={`bar ${i===6?"today":""}`} style={{height:`${d.amount?Math.max(6,d.amount/max*100):2}%`}} title={formatCurrency(d.amount,preferences.currency)}/></div><span>{new Date(`${d.date}T00:00:00`).toLocaleDateString(undefined,{weekday:"short"}).slice(0,2)}</span></div>)}</div><div className="flex justify-between mt-5 text-xs text-[#718078]"><span>Lowest: {formatCurrency(Math.min(...weeklySpending.map(x=>x.amount)),preferences.currency)}</span><span>Highest: {formatCurrency(Math.max(...weeklySpending.map(x=>x.amount)),preferences.currency)}</span></div></section>
  <section className="panel p-6 sm:p-7"><p className="eyebrow">Accounts</p><h2 className="panel-title">Where money lives</h2><div className="mt-5 space-y-3">{accountBalances.map(a=><div key={a.id} className="account-row"><span className="account-dot" style={{background:a.color}}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{a.name}</p><p className="text-[10px] uppercase text-[#6f7c74]">{a.type}</p></div><strong className="mono text-xs">{formatCurrency(a.balance,preferences.currency)}</strong></div>)}</div><Link href="/accounts" className="soft-link mt-4">Manage accounts <ChevronRight size={14}/></Link></section>
 </div>
 <div className="grid gap-5 mt-5 xl:grid-cols-[1.05fr_.95fr]">
  <section className="panel p-6 sm:p-7"><div className="panel-head"><div><p className="eyebrow">Activity</p><h2 className="panel-title">Recent transactions</h2></div><Link href="/transactions" className="soft-link">View all</Link></div><div className="mt-3 divide-y divide-[#2f3933]">{recent.map(t=><Mini key={t.id} t={t} currency={preferences.currency}/>)}</div>{!recent.length&&<Empty text="Your transaction feed will appear here."/>}</section>
  <section className="panel p-6 sm:p-7"><div className="panel-head"><div><p className="eyebrow">Guardrails</p><h2 className="panel-title">Budget health</h2></div><Link href="/budgets" className="soft-link">Manage</Link></div><div className="mt-5 space-y-5">{currentBudgets.slice(0,4).map(b=><div key={b.id}><div className="flex justify-between text-xs"><span>{b.category}</span><span className={b.exceeded?"danger":"muted"}>{formatCurrency(b.spent,preferences.currency)} / {formatCurrency(b.limit,preferences.currency)}</span></div><div className="progress"><div className={b.exceeded?"progress-fill danger-fill":"progress-fill"} style={{width:`${Math.min(100,b.percent)}%`}}/></div><div className="mt-1 text-[10px] text-[#66736c]">{b.exceeded?`${formatCurrency(Math.abs(b.remaining),preferences.currency)} over limit`: `${formatCurrency(b.remaining,preferences.currency)} remaining`}</div></div>)}{!currentBudgets.length&&<Empty text="Create a budget and it will be tracked here automatically."/>}</div></section>
 </div>
 <section className="panel p-6 sm:p-7 mt-5"><div className="panel-head"><div><p className="eyebrow">Goals</p><h2 className="panel-title">What you are building</h2></div><Link href="/goals" className="soft-link">All goals</Link></div><div className="grid gap-4 md:grid-cols-3 mt-5">{goals.slice(0,3).map(g=>{const pct=Math.min(100,g.saved/g.target*100);return <div key={g.id} className="goal-mini"><div className="flex justify-between"><span className="font-semibold text-sm">{g.name}</span><Target size={16} className="text-[#d8e87b]"/></div><div className="mono text-xs mt-4">{formatCurrency(g.saved,preferences.currency)} <span className="muted">/ {formatCurrency(g.target,preferences.currency)}</span></div><div className="progress mt-3"><div className="progress-fill" style={{width:`${pct}%`}}/></div><span className="muted text-[10px] mt-2 block">{pct.toFixed(0)}% complete</span></div>})}{!goals.length&&<Empty text="Create your first savings goal."/>}</div></section>
 <TransactionForm open={open} onClose={()=>setOpen(false)}/>
 </AppShell>
}
function Mini({t,currency}){const income=t.type==="income",transfer=t.type==="transfer";return <div className="transaction-row"><span className={`tx-icon ${income?"income":transfer?"transfer":"expense"}`}>{income?<ArrowDownRight size={17}/>:transfer?<ArrowLeftRight size={17}/>:<ArrowUpRight size={17}/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{t.description}</p><p className="text-[10px] text-[#708078] mt-1">{transfer?"Transfer":t.category} · {formatDate(t.date,{month:"short",day:"numeric"})}</p></div><strong className={`mono text-xs ${income?"positive":""}`}>{income?"+":transfer?"↔":"−"}{formatCurrency(t.amount,currency)}</strong></div>}
function Empty({text}){return <div className="empty-mini"><Wallet size={18}/><span>{text}</span></div>}
