import { useMemo,useState } from "react";
import { CalendarDays, Download, Filter, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import AppShell from "../components/AppShell";import SectionHeader from "../components/SectionHeader";import TransactionForm from "../components/TransactionForm";import {useFinance} from "../context/FinanceContext";import {formatCurrency,formatDate,csvEscape,downloadText} from "../lib/utils";
export default function Transactions(){const {transactions,deleteTransaction,preferences,accounts,CATEGORIES}=useFinance();const [query,setQuery]=useState("");const [type,setType]=useState("all");const [category,setCategory]=useState("all");const [account,setAccount]=useState("all");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);
 const filtered=useMemo(()=>[...transactions].sort((a,b)=>`${b.date}${b.createdAt}`.localeCompare(`${a.date}${a.createdAt}`)).filter(t=>{const q=query.toLowerCase();return(!q||`${t.description} ${t.category} ${t.note||""} ${(t.tags||[]).join(" ")}`.toLowerCase().includes(q))&&(type==="all"||t.type===type)&&(category==="all"||t.category===category)&&(account==="all"||t.accountId===account)&&(from===""||t.date>=from)&&(to===""||t.date<=to)}),[transactions,query,type,category,account,from,to]);
 const exportCsv=()=>downloadText(`transactions-${new Date().toISOString().slice(0,10)}.csv`,["Date,Type,Description,Category,Amount,Account,Note,Tags",...filtered.map(t=>[t.date,t.type,t.description,t.category,t.amount,accounts.find(a=>a.id===t.accountId)?.name||"",t.note,(t.tags||[]).join(" | ")].map(csvEscape).join(","))].join("\n"),"text/csv");
 const clear=()=>{setQuery("");setType("all");setCategory("all");setAccount("all");setFrom("");setTo("")};
 return <AppShell><SectionHeader eyebrow="Your ledger" title="Transactions." description="A searchable, filterable record of every inflow, outflow, and transfer." action={<div className="flex gap-2"><button onClick={exportCsv} className="btn-secondary"><Download size={15}/> Export CSV</button><button onClick={()=>{setEditing(null);setOpen(true)}} className="btn-primary"><Plus size={16}/> Add transaction</button></div>}/>
 <section className="panel p-4 sm:p-5"><div className="grid gap-3 lg:grid-cols-[1fr_auto_auto_auto] items-center"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#64736a]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="input pl-10" placeholder="Search descriptions, notes, tags..."/></div><select value={type} onChange={e=>setType(e.target.value)} className="input"><option value="all">All types</option><option value="expense">Expenses</option><option value="income">Income</option><option value="transfer">Transfers</option></select><select value={category} onChange={e=>setCategory(e.target.value)} className="input"><option value="all">All categories</option>{CATEGORIES.map(c=><option key={c.name}>{c.name}</option>)}</select><select value={account} onChange={e=>setAccount(e.target.value)} className="input"><option value="all">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="grid gap-3 sm:grid-cols-2 mt-3"><label className="date-input"><CalendarDays size={15}/><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="date-input"><CalendarDays size={15}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{(query||type!=="all"||category!=="all"||account!=="all"||from||to)&&<button onClick={clear} className="soft-link mt-3"><X size={13}/> Clear filters</button>}</section>
 <div className="flex items-center justify-between mt-5 mb-3"><span className="muted text-xs"><Filter size={13} className="inline mr-1"/>{filtered.length} of {transactions.length} transactions</span><span className="muted text-xs">Sorted newest first</span></div>
 <section className="panel overflow-hidden">{filtered.map(t=>{const income=t.type==="income",transfer=t.type==="transfer";return <div key={t.id} className="transaction-row px-5 py-4 border-b border-[#2c3630] last:border-0"><span className={`tx-icon ${income?"income":transfer?"transfer":"expense"}`}>{income?"↓":transfer?"↔":"↑"}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-x-2 items-center"><p className="font-semibold text-sm">{t.description}</p>{t.recurring&&<span className="tag">Recurring</span>}</div><p className="text-[11px] text-[#728078] mt-1">{t.type} · {t.category||"Transfer"} · {formatDate(t.date)} · {accounts.find(a=>a.id===t.accountId)?.name||"Unknown account"}</p>{t.note&&<p className="text-[11px] text-[#5f6d65] mt-1 truncate">{t.note}</p>}</div><strong className={`mono text-sm ${income?"positive":""}`}>{income?"+":transfer?"↔":"−"}{formatCurrency(t.amount,preferences.currency)}</strong><button onClick={()=>{setEditing(t);setOpen(true)}} className="icon-btn"><Pencil size={15}/></button><button onClick={()=>deleteTransaction(t.id)} className="icon-btn danger-icon"><Trash2 size={15}/></button></div>})}{!filtered.length&&<div className="empty-state"><Search size={24}/><h3>No transactions found</h3><p>Try changing the filters or add your first transaction.</p></div>}</section>
 <TransactionForm key={editing?.id||"new"} open={open} onClose={()=>setOpen(false)} initial={editing}/></AppShell>}
